version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: boilerplate-graphql-container
    environment:
      MYSQL_DATABASE: 'boilerplate-graphql'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '33060:3306'
    expose:
      - '33060'
    volumes:
      - boilerplate-graphql-volume:/var/lib/mysql
volumes:
  boilerplate-graphql-volume:
